@main def solveAdventDay(day: Int, part: Int): Unit = 
  if day == 1 && part == 1 then println(Day1.partOne())
  else if day == 1 && part == 2 then println(Day1.partTwo())
  else if day == 2 && part == 1 then println(Day2.partOne())
  else if day == 2 && part == 2 then println(Day2.partTwo())
  else if day == 3 && part == 1 then println(Day3.partOne())
  else if day == 3 && part == 2 then println(Day3.partTwo())
  else if day == 4 && part == 1 then println(Day4.partOne())
  else if day == 4 && part == 2 then println(Day4.partTwo())
  else if day == 5 && part == 1 then println(Day5.partOne())
  else if day == 5 && part == 2 then println(Day5.partTwo())
  else if day == 6 && part == 1 then println(Day6.partOne())
  else if day == 6 && part == 2 then println(Day6.partTwo())
  else if day == 7 && part == 1 then println(Day7.partOne())
  else if day == 7 && part == 2 then println(Day7.partTwo())
  else if day == 8 && part == 1 then println(Day8.partOne())
  else if day == 8 && part == 2 then println(Day8.partTwo())
  else if day == 9 && part == 1 then println(Day9.partOne())
  else if day == 9 && part == 2 then println(Day9.partTwo())
  else if day == 10 && part == 1 then println(Day10.partOne())
  else if day == 10 && part == 2 then println(Day10.partTwo())
  else if day == 11 && part == 1 then println(Day11.partOne())
  else if day == 11 && part == 2 then println(Day11.partTwo())
  else if day == 12 && part == 1 then println(Day12.partOne())
  else if day == 12 && part == 2 then println(Day12.partTwo())
  else if day == 13 && part == 1 then println(Day13.partOne())